### ISSUE TITLE
GameCoreConfig改进

### ISSUE THREAD

**Issue by SBLZZ** [Ink-Marks-Studio/StarLight.Core#1]
可以添加VersionType属性，控制VersionType，如果VersionType="auto"那就使用Json文件中读取的VersionType
ArgumentsBuildUtil.cs第171-184行
示例代码：
        GameCoreInfo coreInfo = GameCoreUtil.GetGameCore(VersionId, Root);
        if (VersionType == "auto") { VersionType = coreInfo.Type; }
        var gamePlaceholders = new Dictionary<string, string>
        {
            { "${auth_player_name}", BaseAccount.Name },
            { "${version_name}", VersionId },
            { "${assets_root}", Path.Combine(CurrentExecutingDirectory(Root), "assets") },
            { "${assets_index_name}", coreInfo.Assets },
            { "${auth_uuid}", BaseAccount.Uuid.Replace("-","") },
            { "${auth_access_token}", BaseAccount.AccessToken },
            { "${clientid}", "${clientid}" },
            { "${auth_xuid}", "${auth_xuid}" },
            { "${user_type}", userType },
            { "${version_type}", $"\"{TextUtil.ToTitleCase(VersionType)}\"" }//使用自定义的VersionType(会在游戏主界面的左下角显示)
        };

**Comment by SBLZZ** [comment]
添加属性VersionType

**Comment by SBLZZ** [comment]
VersionType为字符串类型

**Comment by zhi-feng2008** [comment]
后续会做，有时间麻烦提交下具体实现到pr
